CREATE OR REPLACE TABLE clean_order_items AS
SELECT DISTINCT
    ORDER_ITEM_ID,
    ORDER_ID,
    PRODUCT_ID,
    COALESCE(QUANTITY,0) AS QUANTITY,
    COALESCE(UNIT_PRICE,0) AS UNIT_PRICE,
    COALESCE(DISCOUNT_PERCENT,0) AS DISCOUNT_PERCENT
FROM SOURCES.TEST_DATA.ORDER_ITEMS;
