--Data Exploration

-------------------------------ORDERS-------------------------------
DESC TABLE SOURCES.TEST_DATA.ORDERS; --Column headers were not loaded properly
SELECT COUNT(*) FROM SOURCES.TEST_DATA.ORDERS; --33
SELECT * FROM SOURCES.TEST_DATA.ORDERS; --inconsistent format in order_date, NULL as string, null values in order_total and status

--Duplicates in PK
SELECT C1, COUNT(*) FROM 
SOURCES.TEST_DATA.ORDERS
GROUP BY 
C1
HAVING COUNT(*) > 1

--Exact duplicates
SELECT *, COUNT(*) FROM 
SOURCES.TEST_DATA.ORDERS
GROUP BY 
C1,C2,C3,C4,C5,C6
HAVING COUNT(*) > 1

--Order_date formatting (8)
SELECT 
    SUM(CASE WHEN TRY_TO_DATE(C3) IS NULL THEN 1 ELSE 0 END) AS unformatted
FROM SOURCES.TEST_DATA.ORDERS;

--Order_total NULL strings (3)
SELECT * FROM SOURCES.TEST_DATA.ORDERS
WHERE TRY_TO_NUMBER(C4) IS NULL 
  AND C4 IS NOT NULL



-------------------------------CUSTOMERS-------------------------------
DESC TABLE SOURCES.TEST_DATA.CUSTOMERS; 
SELECT COUNT(*) FROM SOURCES.TEST_DATA.CUSTOMERS; --11
SELECT * FROM SOURCES.TEST_DATA.CUSTOMERS; --inconsistent formatting in email, phone, date, null values in certain columns 

SELECT CUSTOMER_ID, COUNT(*) FROM 
SOURCES.TEST_DATA.CUSTOMERS
GROUP BY 
CUSTOMER_ID
HAVING COUNT(*) > 1

SELECT *, COUNT(*) FROM 
SOURCES.TEST_DATA.CUSTOMERS
GROUP BY 
CUSTOMER_ID,
FIRST_NAME,
LAST_NAME,
EMAIL,
PHONE,
REGISTRATION_DATE,
STREET,
CITY,
STATE,
ZIP,
LOYALTY_STATUS
HAVING COUNT(*) > 1

--Unformatted phone (9)
SELECT *
FROM SOURCES.TEST_DATA.CUSTOMERS
WHERE REGEXP_REPLACE(PHONE, '[^0-9]', '') != PHONE;

--Unformatted email (3)
SELECT *
FROM SOURCES.TEST_DATA.CUSTOMERS
WHERE email != LOWER(email);


-------------------------------PRODUCTS-------------------------------
DESC TABLE SOURCES.TEST_DATA.PRODUCTS; 
SELECT COUNT(*) FROM SOURCES.TEST_DATA.PRODUCTS; --26
SELECT * FROM SOURCES.TEST_DATA.PRODUCTS; --PRICE has data type issue and inproper NULLS, stock quantity has nulls, inconsistent date


SELECT PRODUCT_ID, COUNT(*) FROM 
SOURCES.TEST_DATA.PRODUCTS
GROUP BY 
PRODUCT_ID
HAVING COUNT(*) > 1

SELECT *, COUNT(*) FROM 
SOURCES.TEST_DATA.PRODUCTS
GROUP BY 
PRODUCT_ID,
PRODUCT_NAME,
CATEGORY,
PRICE,
SUPPLIER_ID,
STOCK_QUANTITY,
LAST_UPDATED
HAVING COUNT(*) > 1


-------------------------------ITEMS-------------------------------
DESC TABLE SOURCES.TEST_DATA.ORDER_ITEMS; 
SELECT COUNT(*) FROM SOURCES.TEST_DATA.ORDER_ITEMS; --58
SELECT * FROM SOURCES.TEST_DATA.ORDER_ITEMS; --null unit price and discount percent

SELECT ORDER_ITEM_ID, COUNT(*) FROM 
SOURCES.TEST_DATA.ORDER_ITEMS
GROUP BY 
ORDER_ITEM_ID
HAVING COUNT(*) > 1

SELECT *, COUNT(*) FROM 
SOURCES.TEST_DATA.ORDER_ITEMS
GROUP BY 
ORDER_ITEM_ID,
ORDER_ID,
PRODUCT_ID,
QUANTITY,
UNIT_PRICE,
DISCOUNT_PERCENT
HAVING COUNT(*) > 1

--Discount percent and unit price
SELECT 
    SUM(CASE WHEN unit_price IS NULL THEN 1 ELSE 0 END) AS null_unit_price, --2
    SUM(CASE WHEN unit_price = '0' THEN 1 ELSE 0 END) AS zero_unit_price, --0
    SUM(CASE WHEN discount_percent IS NULL THEN 1 ELSE 0 END) AS null_discount_percent, --8
    SUM(CASE WHEN discount_percent = '0' THEN 1 ELSE 0 END) AS zero_discount_percent --28
FROM SOURCES.TEST_DATA.ORDER_ITEMS;
