--Data Exploration

-------------------------------ORDERS-------------------------------
DESC TABLE SOURCES.TEST_DATA.ORDERS; --Column headers were not loaded properly
SELECT COUNT(*) FROM SOURCES.TEST_DATA.ORDERS; --33
SELECT * FROM SOURCES.TEST_DATA.ORDERS; --inconsistent format in order_date, NULL as string, null values in order_total and status

--Duplicates in PK
SELECT C1, COUNT(*) FROM 
SOURCES.TEST_DATA.ORDERS
GROUP BY 
C1
HAVING COUNT(*) > 1

--Exact duplicates
SELECT *, COUNT(*) FROM 
SOURCES.TEST_DATA.ORDERS
GROUP BY 
C1,C2,C3,C4,C5,C6
HAVING COUNT(*) > 1



-------------------------------CUSTOMERS-------------------------------
DESC TABLE SOURCES.TEST_DATA.CUSTOMERS; 
SELECT COUNT(*) FROM SOURCES.TEST_DATA.CUSTOMERS; --11
SELECT * FROM SOURCES.TEST_DATA.CUSTOMERS; --inconsistent formatting in email, phone, date, null values in certain columns 

SELECT CUSTOMER_ID, COUNT(*) FROM 
SOURCES.TEST_DATA.CUSTOMERS
GROUP BY 
CUSTOMER_ID
HAVING COUNT(*) > 1

SELECT *, COUNT(*) FROM 
SOURCES.TEST_DATA.CUSTOMERS
GROUP BY 
CUSTOMER_ID,
FIRST_NAME,
LAST_NAME,
EMAIL,
PHONE,
REGISTRATION_DATE,
STREET,
CITY,
STATE,
ZIP,
LOYALTY_STATUS
HAVING COUNT(*) > 1


-------------------------------PRODUCTS-------------------------------
DESC TABLE SOURCES.TEST_DATA.PRODUCTS; 
SELECT COUNT(*) FROM SOURCES.TEST_DATA.PRODUCTS; --26
SELECT * FROM SOURCES.TEST_DATA.PRODUCTS; --PRICE has data type issue and inproper NULLS, stock quantity has nulls, inconsistent date


SELECT PRODUCT_ID, COUNT(*) FROM 
SOURCES.TEST_DATA.PRODUCTS
GROUP BY 
PRODUCT_ID
HAVING COUNT(*) > 1

SELECT *, COUNT(*) FROM 
SOURCES.TEST_DATA.PRODUCTS
GROUP BY 
PRODUCT_ID,
PRODUCT_NAME,
CATEGORY,
PRICE,
SUPPLIER_ID,
STOCK_QUANTITY,
LAST_UPDATED
HAVING COUNT(*) > 1


-------------------------------ITEMS-------------------------------
DESC TABLE SOURCES.TEST_DATA.ORDER_ITEMS; 
SELECT COUNT(*) FROM SOURCES.TEST_DATA.ORDER_ITEMS; --58
SELECT * FROM SOURCES.TEST_DATA.ORDER_ITEMS; --null unit price and discount percent

SELECT ORDER_ITEM_ID, COUNT(*) FROM 
SOURCES.TEST_DATA.ORDER_ITEMS
GROUP BY 
ORDER_ITEM_ID
HAVING COUNT(*) > 1

SELECT *, COUNT(*) FROM 
SOURCES.TEST_DATA.ORDER_ITEMS
GROUP BY 
ORDER_ITEM_ID,
ORDER_ID,
PRODUCT_ID,
QUANTITY,
UNIT_PRICE,
DISCOUNT_PERCENT
HAVING COUNT(*) > 1


